# Generated by Django 6.0.5 on 2026-06-11 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Name')),
                ('domain', models.CharField(max_length=255)),
                ('cert_path', models.CharField(max_length=512)),
                ('serial', models.CharField(blank=True, help_text='Unique certificate serial number', max_length=128, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('last_renewed', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='valid', max_length=50)),
                ('is_wildcard', models.BooleanField(default=False, help_text='Whether it is a wildcard certificate (*.domain.com)')),
                ('allowed_domains', models.TextField(blank=True, help_text='All domains included in the certificate (SANs)')),
                ('cert_type', models.CharField(choices=[('auto', 'Automatic (acme.sh / CA Server)'), ('manual', 'Manual (Upload files)')], default='auto', help_text='Issuance method: automatic via acme.sh or manual upload', max_length=10)),
                ('is_acme', models.BooleanField(default=True, help_text='Whether the certificate is managed by acme.sh')),
                ('ca_server', models.CharField(default='letsencrypt', help_text='CA Server (e.g., letsencrypt, zerossl)', max_length=100)),
                ('dns_provider', models.CharField(blank=True, help_text='e.g., dns_cf, dns_aws', max_length=50)),
                ('key_type', models.CharField(choices=[('ec-256', 'EC 256 (ECDSA)'), ('rsa2048', 'RSA 2048'), ('rsa4096', 'RSA 4096')], default='ec-256', help_text='Key type and length', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField(blank=True)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TargetServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('ssh_port', models.IntegerField(default=22)),
                ('ssh_user', models.CharField(default='root', max_length=50)),
                ('os_type', models.CharField(choices=[('linux', 'Linux'), ('windows', 'Windows')], default='linux', max_length=10)),
                ('ssh_status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Connected'), ('failure', 'Failed')], default='pending', max_length=20)),
                ('web_server_type', models.CharField(choices=[('none', 'None'), ('nginx', 'Nginx'), ('apache', 'Apache (httpd)'), ('iis', 'IIS (Windows)')], default='none', max_length=20)),
                ('path_type', models.CharField(choices=[('default', 'Default Path'), ('custom', 'Custom Path')], default='default', max_length=20)),
                ('custom_path', models.TextField(blank=True, help_text='Input if custom path is selected (e.g., /etc/nginx/ssl)')),
                ('ssl_config_path', models.CharField(blank=True, help_text='SSL config file path (e.g., /etc/httpd/conf.d/ssl.conf)', max_length=512)),
                ('last_tested', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeployScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('last_executed', models.DateTimeField(blank=True, null=True)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deploy_scripts', to='core_cert.certificate')),
            ],
        ),
        migrations.CreateModel(
            name='DeploymentTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_path', models.TextField(help_text='Remote server path where the certificate will be stored')),
                ('reload_command', models.TextField(blank=True, help_text='e.g., systemctl reload nginx')),
                ('prepare_dir', models.BooleanField(default=True, help_text='Create target directory')),
                ('transfer_files', models.BooleanField(default=True, help_text='Transfer certificate files')),
                ('reload_service', models.BooleanField(default=True, help_text='Run post-processing script (EXEC)')),
                ('include_all_bindings', models.BooleanField(default=False, help_text='Also update the certificate on the 443 binding with an empty host name (Windows only)')),
                ('restart_containers', models.JSONField(blank=True, default=list, help_text='Names of Docker containers to restart after deployment (Linux & Windows)')),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployment_targets', to='core_cert.deployscript')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployment_targets', to='core_cert.targetserver')),
            ],
        ),
        migrations.CreateModel(
            name='DeploymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('is_resolved', models.BooleanField(default=False, help_text='실패 시 해결 여부')),
                ('log_output', models.TextField(blank=True, help_text='전체 요약 로그')),
                ('details', models.JSONField(blank=True, default=dict, help_text='서버별 상세 결과')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_cert.deployscript')),
            ],
        ),
        migrations.CreateModel(
            name='FileMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('fullchain', 'Fullchain (fullchain.cer/pem)'), ('key', 'Private Key (.key/pem)'), ('cert', 'Certificate (.cer/pem)'), ('chain', 'Intermediate chain (domain_chain.cer)'), ('chain_aaa', 'Intermediate chain — AAA cross-sign, legacy (ZeroSSL)'), ('chain_usertrust', 'Intermediate chain — USERTrust cross-sign, legacy (ZeroSSL)'), ('pfx', 'PFX (cert.pfx)'), ('rootca', 'Root CA chain (domain_RootCA.pem)')], max_length=20)),
                ('custom_filename', models.CharField(blank=True, help_text='If empty, default filename will be used.', max_length=255)),
                ('custom_path', models.CharField(blank=True, help_text="If set, this file is sent to this specific path instead of the target's common path. The directory is created automatically. (Linux & Windows)", max_length=512)),
                ('deployment_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_mappings', to='core_cert.deploymenttarget')),
            ],
        ),
        migrations.CreateModel(
            name='TargetServerSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255)),
                ('port', models.IntegerField(default=443, help_text='Service port (usually 443)')),
                ('last_discovered', models.DateTimeField(auto_now=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='core_cert.targetserver')),
            ],
            options={
                'unique_together': {('server', 'domain', 'port')},
            },
        ),
    ]
